production:
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: "<%= ENV["POSTGRES_PORT_5432_TCP_ADDR"] %>"
  port: "<%= ENV["POSTGRES_PORT_5432_TCP_PORT"] %>"
  database: "<%= ENV["POSTGRES_DB"] %>"
  username: "<%= ENV["POSTGRES_USER"] %>"
  password: "<%= ENV["POSTGRES_PASSWORD"] %>"
